# -*- coding: utf-8 -*-
import sys
filepath = r"C:\Users\Ivan\Documents\QuickDaily\app\src\main\java\com\quickdaily\ui\SettingsScreen.kt"
L("")
L("import kotlinx.coroutines.launch")
L("import com.quickdaily.ui.theme.LocalAppDimensions")
L("")
L("private data class TimestampOption(val key: String, val label: String)")
L("private val timestampOptions = listOf(")
L("    TimestampOption(\"none\", \"无时间戳\"),")
L("    TimestampOption(\"time_only\", \"仅时间\"),")
L("    TimestampOption(\"time_only_seconds\", \"时间（含秒）\"),")
L("    TimestampOption(\"list\", \"无序列表\"),")
L("    TimestampOption(\"ordered\", \"有序列表\"),")
L("    TimestampOption(\"list_time\", \"列表+时间\"),")
L("    TimestampOption(\"list_time_seconds\", \"列表+时间（秒）\"),")
L(")")
L("")
L("private data class NamingOption(val key: String, val label: String)")
L("private val namingOptions = listOf(")
L("    NamingOption(\"timestamp_original\", \"时间戳_原名\"),")
L("    NamingOption(\"timestamp_ext\", \"时间戳+扩展名\"),")
L("    NamingOption(\"original\", \"保留原名\"),")
L("    NamingOption(\"custom\", \"自定义格式\"),")
L(")")
L("")
L("private val linkOptions = listOf(")
L("    \"described\" to \"Markdown ![](描述)\",")
L("    \"obsidian_wikilink\" to \"Obsidian ![[双向链接]]\",")
L(")")
L("")
L("@OptIn(ExperimentalMaterial3Api::class, ExperimentalFoundationApi::class)")
L("@Composable")
L("fun SettingsScreen(")
L("    appState: AppState = viewModel(),")
L("    onBack: () -> Unit,")
L("    onExternalLaunch: () -> Unit = {}")
L(") {")
L("    val context = LocalContext.current")
L("    val navBarColorS = MaterialTheme.colorScheme.surface.toArgb()")
L("    SideEffect {")
L("        try {")
L("            val window = (context as? Activity)?.window ?: return@SideEffect")
L("            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {")
L("                window.isNavigationBarContrastEnforced = false")
L("            }")
L("            window.navigationBarColor = navBarColorS")
L("        } catch (_: Exception) { }")
L("    }")
L("")
L("    val config by appState.config.collectAsState()")
L("    val todayPath by appState.todayPath.collectAsState()")
L("")
L("    // ── Local edit state ──")
L("    var vaultPath by remember { mutableStateOf(config.vaultPath) }")
L("    var diaryFolder by remember { mutableStateOf(config.diaryFolder) }")
L("    var dateFormat by remember { mutableStateOf(config.dateFormat) }")
L("    var templatePath by remember { mutableStateOf(config.templatePath) }")
L("    var anchorText by remember { mutableStateOf(config.anchorText) }")
L("    var imageStoragePath by remember { mutableStateOf(config.imageStoragePath) }")
L("")
L("    var obsidianDetected by remember { mutableStateOf(false) }")
L("    var obsidianMsg by remember { mutableStateOf(\"\") }")
L("    val scope = rememberCoroutineScope()")
L("    var widgetImageUri by remember { mutableStateOf(config.widgetImageUri) }")
L("")
L("    // ── Update check state ──")
L("    var isCheckingUpdate by remember { mutableStateOf(false) }")
L("    var updateInfo by remember { mutableStateOf<com.quickdaily.util.ReleaseInfo?>(null) }")
L("    var updateStatus by remember { mutableStateOf(\"\") }")
L("    var updateErrors by remember { mutableStateOf<List<com.quickdaily.util.SourceError>>(emptyList()) }")
L("    var isLatest by remember { mutableStateOf(false) }")
L("")
L("    // ── Tab state ──")
L("    val tabs = listOf(\"日记存储\", \"编辑设置\", \"小部件\", \"其他\")")
L("    val pagerState = rememberPagerState(pageCount = { tabs.size })")
L("")
L("    // ── Picker launchers ──")
L("    val vaultPicker = rememberLauncherForActivityResult(")
L("        ActivityResultContracts.OpenDocumentTree()")
L("    ) { uri: Uri? ->")
L("        uri?.let {")
L("            try {")
L("                context.contentResolver.takePersistableUriPermission(")
L("                    it, Intent.FLAG_GRANT_READ_URI_PERMISSION or")
L("                            Intent.FLAG_GRANT_WRITE_URI_PERMISSION")
L("                )")
L("            } catch (_: Exception) { }")
L("            val path = UriUtil.treeUriToPath(it)")
L("            if (path != null) {")
L("                vaultPath = path")
L("                scope.launch {")
L("                    val obsCfg = appState.loadObsidianConfig(path)")
L("                    val appCfg = appState.loadObsidianAppConfig(path)")
L("                    if (obsCfg != null) {")
L("                        diaryFolder = obsCfg.diaryFolder")
L("                        dateFormat = obsCfg.dateFormat")
L("                        templatePath = obsCfg.templatePath")
L("                        obsidianDetected = true")
L("                        obsidianMsg = \"已读取 Obsidian 配置\"")
L("                        if (appCfg != null) {")
L("                            imageStoragePath = appCfg.attachmentFolderPath.let { if (it == \"/\") \"\" else it.trimStart('/') }")
L("                        }")
L("                        appState.saveConfig(DiaryConfig(")
L("                            vaultPath = path.trim(),")
L("                            diaryFolder = obsCfg.diaryFolder.trim().ifBlank { \"Daily\" },")
L("                            dateFormat = obsCfg.dateFormat.trim().ifBlank { \"YYYY-MM-DD\" },")
L("                            templatePath = obsCfg.templatePath.trim(),")
L("                            anchorText = anchorText,")
L("                            timestampFormat = config.timestampFormat,")
L("                            addAnchorIfMissing = config.addAnchorIfMissing,")
L("                            timestampOrder = config.timestampOrder,")
L("                            enterToSave = config.enterToSave,")
L("                            widgetImageUri = config.widgetImageUri,")
L("                            autoCheckUpdate = config.autoCheckUpdate,")
L("                            filterFrontmatter = config.filterFrontmatter,")
L("                            imageStoragePath = imageStoragePath.trim(),")
L("                            imageNamingFormat = config.imageNamingFormat,")
L("                            imageLinkFormat = if (appCfg?.useMarkdownLinks == true) \"described\" else config.imageLinkFormat,")
L("                            tagAutocomplete = config.tagAutocomplete,")
L("                        ))")
L("                    } else {")
L("                        obsidianDetected = false")
L("                        obsidianMsg = \"未找到 .obsidian/daily-notes.json\"")
L("                    }")
L("                }")
L("            }")
L("        }")
L("    }")
L("")
L("    val imageStoragePicker = rememberLauncherForActivityResult(")
L("        ActivityResultContracts.OpenDocumentTree()")
L("    ) { uri: Uri? ->")
L("        uri?.let {")
L("            try {")
L("                context.contentResolver.takePersistableUriPermission(")
L("                    it, Intent.FLAG_GRANT_READ_URI_PERMISSION or")
L("                            Intent.FLAG_GRANT_WRITE_URI_PERMISSION")
L("                )")
L("            } catch (_: Exception) { }")
L("            val path = UriUtil.treeUriToPath(it)")
L("            if (path != null) {")
L("                imageStoragePath = if (vaultPath.isNotBlank() && path.startsWith(vaultPath)) {")
L("                    path.removePrefix(vaultPath).trimStart('/')")
L("                } else {")
L("                    path")
L("                }")
L("            }")
L("        }")
L("    }")
L("")

L("    val templatePicker = rememberLauncherForActivityResult(")
L("        ActivityResultContracts.OpenDocument()")
L("    ) { uri: Uri? ->")
L("        uri?.let {")
L("            val path = UriUtil.documentUriToPath(it)")
L("            if (path != null) {")
L("                templatePath = if (vaultPath.isNotBlank() && path.startsWith(vaultPath)) {")
L("                    path.removePrefix(vaultPath).trimStart('/')")
L("                } else {")
L("                    path")
L("                }")
L("            }")
L("        }")
L("    }")
L("")
L("    val imagePicker = rememberLauncherForActivityResult(")
L("        ActivityResultContracts.GetContent()")
L("    ) { uri: Uri? ->")
L("        uri?.let { srcUri ->")
L("            try {")
L("                val destFile = File(context.filesDir, \"widget_image.jpg\")")
L("                val inputStream = context.contentResolver.openInputStream(srcUri)")
L("                val outputStream = FileOutputStream(destFile)")
L("                inputStream?.use { input ->")
L("                    outputStream.use { output ->")
L("                        input.copyTo(output)")
L("                    }")
L("                }")
L("                val savedPath = destFile.absolutePath")
L("                widgetImageUri = savedPath")
L("                appState.saveConfig(config.copy(widgetImageUri = \"file://\"))")
L("                QuickNoteWidget.updateAllWidgets(context)")
L("                ShortcutHelper.updateAllShortcuts(context)")
L("            } catch (e: Exception) {")
L("                android.util.Log.e(\"QuickDaily\", \"保存小部件图片失败: \")")
L("            }")
L("        }")
L("    }")
L("")
L("    // ── Helper ──")
L("    fun buildConfig(): DiaryConfig = DiaryConfig(")
L("        vaultPath = vaultPath.trim(),")
L("        diaryFolder = diaryFolder.trim().ifBlank { \"Daily\" },")
L("        dateFormat = dateFormat.trim().ifBlank { \"YYYY-MM-DD\" },")
L("        templatePath = templatePath.trim(),")
L("        anchorText = anchorText,")
L("        timestampFormat = config.timestampFormat,")
L("        addAnchorIfMissing = config.addAnchorIfMissing,")
L("        timestampOrder = config.timestampOrder,")
L("        enterToSave = config.enterToSave,")
L("        widgetImageUri = config.widgetImageUri,")
L("        autoCheckUpdate = config.autoCheckUpdate,")
L("        filterFrontmatter = config.filterFrontmatter,")
L("        imageStoragePath = imageStoragePath.trim(),")
L("        imageNamingFormat = config.imageNamingFormat,")
L("        imageLinkFormat = config.imageLinkFormat,")
L("        imageCustomNamingFormat = config.imageCustomNamingFormat,")
L("        tagAutocomplete = config.tagAutocomplete,")
L("        loggingEnabled = config.loggingEnabled")
L("    )")
L("")
L("    fun saveFull() {")
L("        appState.saveConfig(buildConfig())")
L("    }")
L("")
L("    Scaffold(")
L("        topBar = {")
L("            TopAppBar(")
L("                title = { Text(\"设置\") },")
L("                navigationIcon = {")
L("                    IconButton(onClick = { saveFull(); onBack() }) {")
L("                        Icon(Icons.AutoMirrored.Filled.ArrowBack, \"返回\")")
L("                    }")
L("                },")
L("                actions = {")
L("                    IconButton(onClick = { saveFull(); onBack() }) {")
L("                        Icon(Icons.Default.Check, \"保存\")")
L("                    }")
L("                },")
L("                colors = TopAppBarDefaults.topAppBarColors(")
L("                    containerColor = MaterialTheme.colorScheme.primary,")
L("                    titleContentColor = MaterialTheme.colorScheme.onPrimary,")
L("                    navigationIconContentColor = MaterialTheme.colorScheme.onPrimary,")
L("                    actionIconContentColor = MaterialTheme.colorScheme.onPrimary")
L("                )")
L("            )")
L("        }")
L("    ) { padding ->")
L("        Column(modifier = Modifier.fillMaxSize().padding(padding)) {")
L("            TabRow(selectedTabIndex = pagerState.currentPage) {")
L("                tabs.forEachIndexed { index, title ->")
L("                    Tab(")
L("                        selected = pagerState.currentPage == index,")
L("                        onClick = { scope.launch { pagerState.animateScrollToPage(index) } },")
L("                        text = { Text(title) }")
L("                    )")
L("                }")
L("            }")
L("")
L("            HorizontalPager(")
L("                state = pagerState,")
L("                modifier = Modifier.fillMaxSize()")
L("            ) { page ->")
L("                when (page) {")
L("                    0 -> DiaryStorageTab(")
L("                        vaultPath = vaultPath,")
L("                        diaryFolder = diaryFolder,")
L("                        dateFormat = dateFormat,")
L("                        templatePath = templatePath,")
L("                        imageStoragePath = imageStoragePath,")
L("                        todayPath = todayPath,")
L("                        obsidianDetected = obsidianDetected,")
L("                        obsidianMsg = obsidianMsg,")
L("                        onVaultPathChange = { vaultPath = it },")
L("                        onDiaryFolderChange = { diaryFolder = it },")
L("                        onDateFormatChange = { dateFormat = it },")
L("                        onTemplatePathChange = { templatePath = it },")
L("                        onImageStoragePathChange = { imageStoragePath = it },")
L("                        onReadObsidianConfig = {")
L("                            scope.launch {")
L("                                val obsCfg = appState.loadObsidianConfig(vaultPath)")
L("                                val appCfg = appState.loadObsidianAppConfig(vaultPath)")
L("                                if (obsCfg != null) {")
L("                                    diaryFolder = obsCfg.diaryFolder")
L("                                    dateFormat = obsCfg.dateFormat")
L("                                    templatePath = obsCfg.templatePath")
L("                                    obsidianDetected = true")
L("                                    obsidianMsg = \"已读取 Obsidian 配置\"")
L("                                    if (appCfg != null) {")
L("                                        imageStoragePath = appCfg.attachmentFolderPath.let { if (it == \"/\") \"\" else it.trimStart('/') }")
L("                                        appState.saveConfig(config.copy(")
L("                                            imageLinkFormat = if (appCfg.useMarkdownLinks) \"described\" else \"obsidian_wikilink\"")
L("                                        ))")
L("                                    }")
L("                                } else {")
L("                                    obsidianDetected = false")
L("                                    obsidianMsg = \"未找到 .obsidian/daily-notes.json\"")
L("                                }")
L("                            }")
L("                        },")
L("                        onPickVault = { onExternalLaunch(); vaultPicker.launch(null) },")
L("                        onPickTemplate = { onExternalLaunch(); templatePicker.launch(arrayOf(\"text/markdown\", \"text/plain\", \"*/*\")) },")
L("                        onPickImageStorage = { onExternalLaunch(); imageStoragePicker.launch(null) },")
L("                        onSave = { saveFull(); onBack() },")
L("                        vaultEnabled = vaultPath.isNotBlank()")
L("                    )")
L("                    1 -> EditorSettingsTab(")
L("                        config = config,")
L("                        anchorText = anchorText,")
L("                        onAnchorTextChange = { anchorText = it },")
L("                        onConfigChange = { newCfg -> appState.saveConfig(newCfg) },")
L("                        onSave = { saveFull() }")
L("                    )")
L("                    2 -> WidgetsTab(")
L("                        widgetImageUri = widgetImageUri,")
L("                        context = context,")
L("                        onPickImage = { onExternalLaunch(); imagePicker.launch(\"image/*\") },")
L("                        onSave = { saveFull() }")
L("                    )")
L("                    3 -> OtherTab(")
L("                        config = config,")
L("                        isCheckingUpdate = isCheckingUpdate,")
L("                        updateInfo = updateInfo,")
L("                        updateStatus = updateStatus,")
L("                        updateErrors = updateErrors,")
L("                        isLatest = isLatest,")
L("                        context = context,")
L("                        onConfigChange = { newCfg -> appState.saveConfig(newCfg) },")
L("                        onCheckUpdate = {")
L("                            isCheckingUpdate = true")
L("                            updateInfo = null")
L("                            updateErrors = emptyList()")
L("                            isLatest = false")
L("                            updateStatus = \"正在检查更新...\"")
L("                            scope.launch {")
L("                                val result = com.quickdaily.util.UpdateChecker.checkUpdate(")
L("                                    currentVersion = BuildConfig.VERSION_NAME, context = context")
L("                                ) { progress -> updateStatus = progress }")
L("                                when (result) {")
L("                                    is com.quickdaily.util.UpdateResult.UpdateAvailable -> {")
L("                                        updateInfo = result.info; updateStatus = \"\"")
L("                                    }")
L("                                    com.quickdaily.util.UpdateResult.UpToDate -> {")
L("                                        isLatest = true; updateStatus = \"\"")
L("                                    }")
L("                                    is com.quickdaily.util.UpdateResult.Failed -> {")
L("                                        updateErrors = result.errors; updateStatus = \"\"")
L("                                    }")
L("                                    else -> { updateStatus = \"\" }")
L("                                }")
L("                                isCheckingUpdate = false")
L("                            }")
L("                        }")
L("                    )")
L("                }")
L("            }")
L("        }")
L("    }")
L("}")
L("")

L("// ══════════════════════════════════════════════════════════")
L("// Tab 1: Diary Storage")
L("// ══════════════════════════════════════════════════════════")
L("")
L("@Composable")
L("private fun DiaryStorageTab(")
L("    vaultPath: String,")
L("    diaryFolder: String,")
L("    dateFormat: String,")
L("    templatePath: String,")
L("    imageStoragePath: String,")
L("    todayPath: String,")
L("    obsidianDetected: Boolean,")
L("    obsidianMsg: String,")
L("    onVaultPathChange: (String) -> Unit,")
L("    onDiaryFolderChange: (String) -> Unit,")
L("    onDateFormatChange: (String) -> Unit,")
L("    onTemplatePathChange: (String) -> Unit,")
L("    onImageStoragePathChange: (String) -> Unit,")
L("    onReadObsidianConfig: () -> Unit,")
L("    onPickVault: () -> Unit,")
L("    onPickTemplate: () -> Unit,")
L("    onPickImageStorage: () -> Unit,")
L("    onSave: () -> Unit,")
L("    vaultEnabled: Boolean,")
L(") {")
L("    Column(")
L("        modifier = Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),")
L("        verticalArrangement = Arrangement.spacedBy(12.dp)")
L("    ) {")
L("        Text(\"仓库配置\", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.primary)")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {")
L("                OutlinedTextField(")
L("                    value = vaultPath,")
L("                    onValueChange = onVaultPathChange,")
L("                    label = { Text(\"Obsidian 仓库路径\") },")
L("                    placeholder = { Text(\"/storage/emulated/0/Documents/Vault\") },")
L("                    modifier = Modifier.fillMaxWidth(),")
L("                    singleLine = true,")
L("                    leadingIcon = { Icon(Icons.Default.Storage, null, Modifier.size(20.dp)) },")
L("                    trailingIcon = {")
L("                        IconButton(onClick = onPickVault) {")
L("                            Icon(Icons.Default.FolderOpen, \"选择文件夹\")")
L("                        }")
L("                    }")
L("                )")
L("")
L("                FilledTonalButton(onClick = onReadObsidianConfig, modifier = Modifier.fillMaxWidth()) {")
L("                    Icon(Icons.Default.Folder, null, Modifier.size(18.dp))")
L("                    Spacer(Modifier.width(8.dp))")
L("                    Text(\"从 Obsidian 读取配置\")")
L("                }")
L("                if (obsidianMsg.isNotEmpty()) {")
L("                    Text(obsidianMsg,")
L("                        color = if (obsidianDetected) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.error,")
L("                        style = MaterialTheme.typography.bodySmall)")
L("                }")
L("")
L("                HorizontalDivider()")
L("")
L("                OutlinedTextField(")
L("                    value = imageStoragePath,")
L("                    onValueChange = onImageStoragePathChange,")
L("                    label = { Text(\"图片储存目录\") },")
L("                    placeholder = { Text(\"assets/images（相对仓库路径）\") },")
L("                    modifier = Modifier.fillMaxWidth(),")
L("                    singleLine = true,")
L("                    leadingIcon = { Icon(Icons.Default.PhotoLibrary, null, Modifier.size(20.dp)) },")
L("                    trailingIcon = {")
L("                        IconButton(onClick = onPickImageStorage) {")
L("                            Icon(Icons.Default.FolderOpen, \"选择文件夹\")")
L("                        }")
L("                    }")
L("                )")
L("            }")
L("        }")
L("")
L("        Text(\"日记文件配置\", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.primary)")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {")
L("                OutlinedTextField(")
L("                    value = diaryFolder,")
L("                    onValueChange = onDiaryFolderChange,")
L("                    label = { Text(\"日记文件夹\") },")
L("                    placeholder = { Text(\"Daily\") },")
L("                    modifier = Modifier.fillMaxWidth(),")
L("                    singleLine = true")
L("                )")
L("                OutlinedTextField(")
L("                    value = dateFormat,")
L("                    onValueChange = onDateFormatChange,")
L("                    label = { Text(\"日记文件名格式\") },")
L("                    placeholder = { Text(\"YYYY-MM-DD\") },")
L("                    modifier = Modifier.fillMaxWidth(),")
L("                    singleLine = true")
L("                )")
L("                OutlinedTextField(")
L("                    value = templatePath,")
L("                    onValueChange = onTemplatePathChange,")
L("                    label = { Text(\"日记模板路径\") },")
L("                    placeholder = { Text(\"Templates/daily.md（可选）\") },")
L("                    modifier = Modifier.fillMaxWidth(),")
L("                    singleLine = true,")
L("                    leadingIcon = { Icon(Icons.Default.Description, null, Modifier.size(20.dp)) },")
L("                    trailingIcon = {")
L("                        IconButton(onClick = onPickTemplate) {")
L("                            Icon(Icons.Default.FileOpen, \"选择文件\")")
L("                        }")
L("                    }")
L("                )")
L("            }")
L("        }")
L("")
L("        Card(modifier = Modifier.fillMaxWidth(), colors = CardDefaults.cardColors(")
L("            containerColor = MaterialTheme.colorScheme.surfaceVariant")
L("        )) {")
L("            Column(modifier = Modifier.padding(16.dp)) {")
L("                Text(\"今天的日记路径\", style = MaterialTheme.typography.labelMedium)")
L("                Spacer(Modifier.height(4.dp))")
L("                Text(todayPath.ifEmpty { \"(输入 vault 路径后自动计算)\" },")
L("                    style = MaterialTheme.typography.bodySmall,")
L("                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f))")
L("            }")
L("        }")
L("")
L("        Button(onClick = onSave, modifier = Modifier.fillMaxWidth(), enabled = vaultEnabled) {")
L("            Icon(Icons.Default.Check, null, Modifier.size(18.dp))")
L("            Spacer(Modifier.width(8.dp))")
L("            Text(\"保存并返回\")")
L("        }")
L("    }")
L("}")
L("")

L("// ══════════════════════════════════════════════════════════")
L("// Tab 2: Editor Settings")
L("// ══════════════════════════════════════════════════════════")
L("")
L("@OptIn(ExperimentalMaterial3Api::class)")
L("@Composable")
L("private fun EditorSettingsTab(")
L("    config: DiaryConfig,")
L("    anchorText: String,")
L("    onAnchorTextChange: (String) -> Unit,")
L("    onConfigChange: (DiaryConfig) -> Unit,")
L("    onSave: () -> Unit,")
L(") {")
L("    Column(")
L("        modifier = Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),")
L("        verticalArrangement = Arrangement.spacedBy(12.dp)")
L("    ) {")
L("        Text(\"时间戳设置\", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.primary)")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {")
L("                DropdownSetting(")
L("                    label = \"时间戳格式\",")
L("                    selectedKey = config.timestampFormat,")
L("                    options = timestampOptions.map { it.key to it.label },")
L("                    onSelect = { onConfigChange(config.copy(timestampFormat = it)) }")
L("                )")
L("")
L("                Text(\"时间戳插入顺序\", style = MaterialTheme.typography.bodyMedium)")
L("                SingleChoiceSegmentedButtonRow(modifier = Modifier.fillMaxWidth()) {")
L("                    SegmentedButton(")
L("                        selected = config.timestampOrder == \"above\",")
L("                        onClick = { onConfigChange(config.copy(timestampOrder = \"above\")) },")
L("                        shape = SegmentedButtonDefaults.itemShape(index = 0, count = 2)")
L("                    ) { Text(\"锚点上方\") }")
L("                    SegmentedButton(")
L("                        selected = config.timestampOrder == \"below\",")
L("                        onClick = { onConfigChange(config.copy(timestampOrder = \"below\")) },")
L("                        shape = SegmentedButtonDefaults.itemShape(index = 1, count = 2)")
L("                    ) { Text(\"锚点下方\") }")
L("                }")
L("")
L("                OutlinedTextField(")
L("                    value = anchorText,")
L("                    onValueChange = onAnchorTextChange,")
L("                    label = { Text(\"锚点文本\") },")
L("                    placeholder = { Text(\"## 今日速记\") },")
L("                    modifier = Modifier.fillMaxWidth(),")
L("                    singleLine = true,")
L("                    leadingIcon = { Icon(Icons.Default.TextFormat, null, Modifier.size(20.dp)) }")
L("                )")
L("")
L("                ListItem(")
L("                    headlineContent = { Text(\"无锚点时自动添加\") },")
L("                    trailingContent = {")
L("                        Switch(checked = config.addAnchorIfMissing, onCheckedChange = {")
L("                            onConfigChange(config.copy(addAnchorIfMissing = it))")
L("                        })")
L("                    },")
L("                    modifier = Modifier.heightIn(min = 48.dp)")
L("                )")
L("            }")
L("        }")
L("")
L("        Text(\"编辑器设置\", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.primary)")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(horizontal = 0.dp)) {")
L("                ListItem(")
L("                    headlineContent = { Text(\"回车保存\") },")
L("                    supportingContent = { Text(\"在编辑器中按回车键快速保存\") },")
L("                    trailingContent = {")
L("                        Switch(checked = config.enterToSave, onCheckedChange = {")
L("                            onConfigChange(config.copy(enterToSave = it))")
L("                        })")
L("                    }")
L("                )")
L("                HorizontalDivider(modifier = Modifier.padding(horizontal = 16.dp))")
L("                ListItem(")
L("                    headlineContent = { Text(\"过滤 Frontmatter\") },")
L("                    supportingContent = { Text(\"编辑时隐藏日记文件头部元数据\") },")
L("                    trailingContent = {")
L("                        Switch(checked = config.filterFrontmatter, onCheckedChange = {")
L("                            onConfigChange(config.copy(filterFrontmatter = it))")
L("                        })")
L("                    }")
L("                )")
L("                HorizontalDivider(modifier = Modifier.padding(horizontal = 16.dp))")
L("                ListItem(")
L("                    headlineContent = { Text(\"标签自动补全\") },")
L("                    supportingContent = { Text(\"输入 # 时提示已有标签\") },")
L("                    trailingContent = {")
L("                        Switch(checked = config.tagAutocomplete, onCheckedChange = {")
L("                            onConfigChange(config.copy(tagAutocomplete = it))")
L("                        })")
L("                    }")
L("                )")
L("            }")
L("        }")
L("")
L("        Text(\"图片设置\", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.primary)")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {")
L("                DropdownSetting(")
L("                    label = \"图片命名格式\",")
L("                    selectedKey = config.imageNamingFormat,")
L("                    options = namingOptions.map { it.key to it.label },")
L("                    onSelect = { onConfigChange(config.copy(imageNamingFormat = it)) }")
L("                )")
L("                if (config.imageNamingFormat == \"custom\") {")
L("                    OutlinedTextField(")
L("                        value = config.imageCustomNamingFormat,")
L("                        onValueChange = { onConfigChange(config.copy(imageCustomNamingFormat = it)) },")
L("                        label = { Text(\"自定义命名格式\") },")
L("                        modifier = Modifier.fillMaxWidth(),")
L("                        singleLine = true")
L("                    )")
L("                }")
L("                DropdownSetting(")
L("                    label = \"图片链接格式\",")
L("                    selectedKey = config.imageLinkFormat,")
L("                    options = linkOptions,")
L("                    onSelect = { onConfigChange(config.copy(imageLinkFormat = it)) }")
L("                )")
L("            }")
L("        }")
L("")
L("        Spacer(Modifier.height(8.dp))")
L("        FilledTonalButton(onClick = onSave, modifier = Modifier.fillMaxWidth()) {")
L("            Icon(Icons.Default.Check, null, Modifier.size(18.dp))")
L("            Spacer(Modifier.width(8.dp))")
L("            Text(\"保存设置\")")
L("        }")
L("    }")
L("}")
L("")

L("// ══════════════════════════════════════════════════════════")
L("// Tab 3: Widgets & Shortcuts")
L("// ══════════════════════════════════════════════════════════")
L("")
L("@Composable")
L("private fun WidgetsTab(")
L("    widgetImageUri: String,")
L("    context: android.content.Context,")
L("    onPickImage: () -> Unit,")
L("    onSave: () -> Unit,")
L(") {")
L("    Column(")
L("        modifier = Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),")
L("        verticalArrangement = Arrangement.spacedBy(12.dp)")
L("    ) {")
L("        Text(\"小部件与快捷方式\", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.primary)")
L("")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {")
L("                Text(\"小部件自定义图标\", style = MaterialTheme.typography.titleSmall)")
L("                Text(\"选择一张图片作为快速添加小部件和桌面图标的图标\",")
L("                    style = MaterialTheme.typography.bodySmall,")
L("                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f))")
L("")
L("                Row(")
L("                    verticalAlignment = Alignment.CenterVertically,")
L("                    modifier = Modifier.fillMaxWidth()")
L("                ) {")
L("                    Surface(")
L("                        modifier = Modifier.size(64.dp),")
L("                        shape = MaterialTheme.shapes.small,")
L("                        tonalElevation = 2.dp")
L("                    ) {")
L("                        if (widgetImageUri.isNotEmpty()) {")
L("                            val bitmap = remember(widgetImageUri) {")
L("                                try {")
L("                                    val path = widgetImageUri.removePrefix(\"file://\")")
L("                                    BitmapFactory.decodeFile(path)")
L("                                } catch (_: Exception) { null }")
L("                            }")
L("                            if (bitmap != null) {")
L("                                Image(")
L("                                    bitmap = bitmap.asImageBitmap(),")
L("                                    contentDescription = \"当前图标\",")
L("                                    modifier = Modifier.fillMaxSize().padding(4.dp),")
L("                                    contentScale = ContentScale.Fit")
L("                                )")
L("                            } else {")
L("                                Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {")
L("                                    Icon(Icons.Default.Widgets, null, Modifier.size(32.dp),")
L("                                        tint = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.38f))")
L("                                }")
L("                            }")
L("                        } else {")
L("                            Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {")
L("                                Icon(Icons.Default.Widgets, null, Modifier.size(32.dp),")
L("                                    tint = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.38f))")
L("                            }")
L("                        }")
L("                    }")
L("")
L("                    Spacer(Modifier.width(16.dp))")
L("")
L("                    FilledTonalButton(onClick = onPickImage) {")
L("                        Icon(Icons.Default.AddAPhoto, null, Modifier.size(18.dp))")
L("                        Spacer(Modifier.width(8.dp))")
L("                        Text(if (widgetImageUri.isNotEmpty()) \"更换图片\" else \"选择图片\")")
L("                    }")
L("                }")
L("            }")
L("        }")
L("")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {")
L("                Text(\"添加快捷方式\", style = MaterialTheme.typography.titleSmall)")
L("")
L("                FilledTonalButton(")
L("                    onClick = { ShortcutHelper.requestPinShortcut(context) },")
L("                    modifier = Modifier.fillMaxWidth()")
L("                ) {")
L("                    Icon(Icons.Default.Shortcut, null, Modifier.size(18.dp))")
L("                    Spacer(Modifier.width(8.dp))")
L("                    Text(\"快速添加（桌面图标）\")")
L("                }")
L("")
L("                FilledTonalButton(")
L("                    onClick = {")
L("                        try {")
L("                            val mgr = android.appwidget.AppWidgetManager.getInstance(context)")
L("                            val comp = android.content.ComponentName(context, QuickNoteWidget::class.java)")
L("                            if (mgr.isRequestPinAppWidgetSupported) {")
L("                                val cb = android.app.PendingIntent.getBroadcast(context, 2, Intent(), android.app.PendingIntent.FLAG_IMMUTABLE)")
L("                                mgr.requestPinAppWidget(comp, null, cb)")
L("                            } else {")
L("                                context.startActivity(Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_HOME))")
L("                            }")
L("                        } catch (_: Exception) {")
L("                            context.startActivity(Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_HOME))")
L("                        }")
L("                    },")
L("                    modifier = Modifier.fillMaxWidth()")
L("                ) {")
L("                    Icon(Icons.Default.Widgets, null, Modifier.size(18.dp))")
L("                    Spacer(Modifier.width(8.dp))")
L("                    Text(\"快速添加（小部件）\")")
L("                }")
L("")
L("                FilledTonalButton(")
L("                    onClick = {")
L("                        try {")
L("                            val mgr = android.appwidget.AppWidgetManager.getInstance(context)")
L("                            val comp = android.content.ComponentName(context, TaskWidget::class.java)")
L("                            if (mgr.isRequestPinAppWidgetSupported) {")
L("                                val cb = android.app.PendingIntent.getBroadcast(context, 3, Intent(), android.app.PendingIntent.FLAG_IMMUTABLE)")
L("                                mgr.requestPinAppWidget(comp, null, cb)")
L("                            } else {")
L("                                context.startActivity(Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_HOME))")
L("                            }")
L("                        } catch (_: Exception) {")
L("                            context.startActivity(Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_HOME))")
L("                        }")
L("                    },")
L("                    modifier = Modifier.fillMaxWidth()")
L("                ) {")
L("                    Icon(Icons.Default.EditNote, null, Modifier.size(18.dp))")
L("                    Spacer(Modifier.width(8.dp))")
L("                    Text(\"今日任务（小部件）\")")
L("                }")
L("            }")
L("        }")
L("")
L("        Text(")
L("            \"自定义图标同时应用于快速添加的小部件和桌面图标。如点击无反应，请给予本APP创建桌面图标的权限。\",")
L("            style = MaterialTheme.typography.bodySmall,")
L("            color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f)")
L("        )")
L("")
L("        Spacer(Modifier.height(8.dp))")
L("        FilledTonalButton(onClick = onSave, modifier = Modifier.fillMaxWidth()) {")
L("            Icon(Icons.Default.Check, null, Modifier.size(18.dp))")
L("            Spacer(Modifier.width(8.dp))")
L("            Text(\"保存设置\")")
L("        }")
L("    }")
L("}")
L("")

L("// ══════════════════════════════════════════════════════════")
L("// Tab 4: Other (Updates, Accessibility, About)")
L("// ══════════════════════════════════════════════════════════")
L("")
L("@Composable")
L("private fun OtherTab(")
L("    config: DiaryConfig,")
L("    isCheckingUpdate: Boolean,")
L("    updateInfo: com.quickdaily.util.ReleaseInfo?,")
L("    updateStatus: String,")
L("    updateErrors: List<com.quickdaily.util.SourceError>,")
L("    isLatest: Boolean,")
L("    context: android.content.Context,")
L("    onConfigChange: (DiaryConfig) -> Unit,")
L("    onCheckUpdate: () -> Unit,")
L(") {")
L("    Column(")
L("        modifier = Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),")
L("        verticalArrangement = Arrangement.spacedBy(12.dp)")
L("    ) {")
L("        Text(\"更新设置\", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.primary)")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(horizontal = 0.dp)) {")
L("                ListItem(")
L("                    headlineContent = { Text(\"启动时自动检查更新\") },")
L("                    supportingContent = { Text(\"每次启动应用时自动检测 GitHub 最新版本\") },")
L("                    trailingContent = {")
L("                        Switch(checked = config.autoCheckUpdate, onCheckedChange = {")
L("                            onConfigChange(config.copy(autoCheckUpdate = it))")
L("                        })")
L("                    }")
L("                )")
L("            }")
L("        }")
L("")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {")
L("                Button(onClick = onCheckUpdate, modifier = Modifier.fillMaxWidth(), enabled = !isCheckingUpdate) {")
L("                    Icon(Icons.Default.Update, null, Modifier.size(18.dp))")
L("                    Spacer(Modifier.width(8.dp))")
L("                    Text(if (isCheckingUpdate) updateStatus.ifEmpty { \"检查中...\" } else \"检查更新\")")
L("                }")
L("                if (isCheckingUpdate && updateStatus.isNotEmpty()) {")
L("                    Text(updateStatus, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.primary)")
L("                }")
L("                if (updateInfo != null) {")
L("                    Text(\"发现新版本：\", style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.primary)")
L("                    Text(updateInfo.body, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f))")
L("                    Button(onClick = { com.quickdaily.util.UpdateChecker.openReleasePage(context, updateInfo.releaseUrl) }, modifier = Modifier.fillMaxWidth()) {")
L("                        Text(\"前往下载\")")
L("                    }")
L("                }")
L("                if (isLatest) {")
L("                    Text(\"当前已是最新版本（）\", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.primary)")
L("                }")
L("                if (updateErrors.isNotEmpty()) {")
L("                    Text(\"检查更新失败，已尝试  个镜像源：\", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.error)")
L("                    updateErrors.forEach { err ->")
L("                        Text(\"? ：\", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.error.copy(alpha = 0.8f), modifier = Modifier.padding(start = 8.dp))")
L("                    }")
L("                }")
L("            }")
L("        }")
L("")
L("        Text(\"辅助服务\", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.primary)")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {")
L("                val accReady = com.quickdaily.QuickAccessibilityService.isAvailable(context)")
L("                Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth()) {")
L("                    Icon(Icons.Default.AccessibilityNew, null, Modifier.size(20.dp), tint = MaterialTheme.colorScheme.primary)")
L("                    Spacer(Modifier.width(12.dp))")
L("                    Column(modifier = Modifier.weight(1f)) {")
L("                        Text(\"速记辅助服务\", style = MaterialTheme.typography.bodyMedium)")
L("                        Text(if (accReady) \"已开启\" else \"未开启\", style = MaterialTheme.typography.bodySmall, color = if (accReady) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.error)")
L("                    }")
L("                }")
L("                Text(\"通知面板快捷磁贴点击后，需要此服务模拟返回键收起通知面板。如未开启，点击磁贴后会弹出提示并跳转设置页。\", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f))")
L("                FilledTonalButton(")
L("                    onClick = { try { context.startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS).apply { flags = Intent.FLAG_ACTIVITY_NEW_TASK }) } catch (_: Exception) { } },")
L("                    modifier = Modifier.fillMaxWidth()")
L("                ) {")
L("                    Text(if (accReady) \"前往无障碍设置\" else \"开启速记辅助服务\")")
L("                }")
L("            }")
L("        }")
L("")
L("        Text(\"日志\", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.primary)")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(horizontal = 0.dp)) {")
L("                ListItem(")
L("                    headlineContent = { Text(\"记录日志\") },")
L("                    supportingContent = { Text(\"日志保存到 Document/QuickDaily_log_日期.txt\") },")
L("                    trailingContent = {")
L("                        Switch(checked = config.loggingEnabled, onCheckedChange = {")
L("                            onConfigChange(config.copy(loggingEnabled = it))")
L("                            com.quickdaily.BetaLogger.configure(context, it, true)")
L("                        })")
L("                    }")
L("                )")
L("            }")
L("        }")
L("")
L("        if (config.loggingEnabled) {")
L("            Button(onClick = { com.quickdaily.BetaLogger.shareLog(context) }, modifier = Modifier.fillMaxWidth()) {")
L("                Icon(Icons.Default.BugReport, null, Modifier.size(18.dp))")
L("                Spacer(Modifier.width(8.dp))")
L("                Text(\"分享 Beta 日志\")")
L("            }")
L("        }")
L("")
L("        Text(\"关于\", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.primary)")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {")
L("                Text(\"QuickDaily \", style = MaterialTheme.typography.titleMedium)")
L("")
L("                Text(\"更新内容：\", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f))")
L("                Text(\"1.5:\\n\" +")
L("                    \"? 新增 首页/悬浮窗 底部工具栏 \\n\" +")
L("                    \"? 新增 首页 阅读视图图片显示 \\n\" +")
L("                    \"? 新增 对 Templater 插件日期格式支持 \\n\" +")
L("                    \"? 新增 安卓小部件添加页面 预览图 \\n\" +")
L("                    \"? 调整 快速添加（桌面图标）的默认图标样式 \\n\" +")
L("                    \"? 修复 悬浮窗 任务切换格式错误 \\n\" +")
L("                    \"? 修复 悬浮窗 空任务异常触发保存 \\n\" +")
L("                    \"? 修复 小部件 今日任务刷新异常 \\n\\n\" +")
L("                    \"1.4:\\n\" +")
L("                    \"? 新增 Frontmatter 过滤 \\n\" +")
L("                    \"? 新增 WW 等日期格式支持 \\n\" +")
L("                    \"? 新增 悬浮窗增加图片录入功能（可批量导入）\\n\" +")
L("                    \"? 新增 悬浮窗增加任务录入功能（双击切换任务状态） \\n\" +")
L("                    \"? 新增 《今日任务》桌面小部件 \\n\\n\" +")
L("                    \"1.3:\\n\" +")
L("                    \"? 新增 7种时间戳格式设置，可适配Thino/Knomo \\n\" +")
L("                    \"? 新增 时间戳文本插入顺序\\n\" +")
L("                    \"? 新增 无锚点时自动添加锚点文本\\n\" +")
L("                    \"? 修复 清空日记内容后无法重新加载模板\\n\" +")
L("                    \"? 修复 每日首次录入内容时略过日记模板\\n\\n\" +")
L("                    \"1.2:\\n\" +")
L("                    \"? 新增 快速添加（桌面图标）\\n\" +")
L("                    \"? 修复 磁贴点击后收回状态栏\\n\\n\" +")
L("                    \"1.1:\\n\" +")
L("                    \"? 新增 小部件时间戳，回车保存\\n\" +")
L("                    \"? 新增 小部件自定义图片\\n\" +")
L("                    \"? 新增 状态栏快捷磁贴\\n\" +")
L("                    \"? 新增 文本分享至本应用\\n\" +")
L("                    \"? 新增 检测更新\\n\\n\" +")
L("                    \"1.0:\\n\" +")
L("                    \"? 正式发布！APP 更名为 QuickDaily\\n\" +")
L("                    \"? 开源发布到 GitHub\",")
L("                    style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f))")
L("")
L("                val coolapkA = buildAnnotatedString {")
L("                    withStyle(SpanStyle(color = MaterialTheme.colorScheme.primary, fontSize = 14.sp)) { append(\"酷安 @附近的人\") }")
L("                }")
L("                ClickableText(text = coolapkA, onClick = { context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(\"https://www.coolapk.com/u/400522\"))) })")
L("")
L("                val githubA = buildAnnotatedString {")
L("                    withStyle(SpanStyle(color = MaterialTheme.colorScheme.primary, fontSize = 14.sp)) { append(\"GitHub @agarcabin\") }")
L("                }")
L("                ClickableText(text = githubA, onClick = { context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(\"https://github.com/agarcabin/QuickDaily\"))) })")
L("")
L("                val qqA = buildAnnotatedString {")
L("                    withStyle(SpanStyle(color = MaterialTheme.colorScheme.primary, fontSize = 14.sp)) { append(\"QQ群：1050092886\") }")
L("                }")
L("                ClickableText(text = qqA, onClick = {")
L("                    val qi = Intent(Intent.ACTION_VIEW, Uri.parse(\"mqqapi://card/show_pslcard?src_type=internal&version=1&uin=1050092886&card_type=group&source=qrcode\"))")
L("                    try { context.startActivity(qi) }")
L("                    catch (_: Exception) {")
L("                        try { context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(\"https://qm.qq.com/cgi-bin/qm/qr?from=app&p=android&jump_from=webapi&k=20251120\"))) }")
L("                        catch (_: Exception) { android.widget.Toast.makeText(context, \"请安装 QQ 或手动搜索群号 1050092886\", android.widget.Toast.LENGTH_LONG).show() }")
L("                    }")
L("                })")
L("            }")
L("        }")
L("")
L("        Card(modifier = Modifier.fillMaxWidth()) {")
L("            Column(modifier = Modifier.padding(16.dp), horizontalAlignment = Alignment.CenterHorizontally) {")
L("                Text(\"如果您喜欢 QuickDaily，可以扫码支持：\", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f))")
L("                Spacer(Modifier.height(8.dp))")
L("                Box(")
L("                    modifier = Modifier.size(240.dp).combinedClickable(")
L("                        onClick = {},")
L("                        onLongClick = {")
L("                            try {")
L("                                val bm = BitmapFactory.decodeResource(context.resources, R.drawable.qr_donate)")
L("                                val fn = \"QuickDaily_donate_.jpg\"")
L("                                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {")
L("                                    val vals = ContentValues().apply {")
L("                                        put(MediaStore.Images.Media.DISPLAY_NAME, fn)")
L("                                        put(MediaStore.Images.Media.MIME_TYPE, \"image/jpeg\")")
L("                                        put(MediaStore.Images.Media.RELATIVE_PATH, Environment.DIRECTORY_PICTURES)")
L("                                        put(MediaStore.Images.Media.IS_PENDING, 1)")
L("                                    }")
L("                                    val uri = context.contentResolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, vals)")
L("                                    uri?.let {")
L("                                        context.contentResolver.openOutputStream(it)?.use { out -> bm.compress(Bitmap.CompressFormat.JPEG, 95, out) }")
L("                                        vals.clear(); vals.put(MediaStore.Images.Media.IS_PENDING, 0)")
L("                                        context.contentResolver.update(it, vals, null, null)")
L("                                    }")
L("                                } else {")
L("                                    @Suppress(\"DEPRECATION\")")
L("                                    val dir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES); dir.mkdirs()")
L("                                    val file = File(dir, fn); FileOutputStream(file).use { out -> bm.compress(Bitmap.CompressFormat.JPEG, 95, out) }")
L("                                    context.sendBroadcast(Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.fromFile(file)))")
L("                                }")
L("                                android.widget.Toast.makeText(context, \"已保存至相册，谢谢！\", android.widget.Toast.LENGTH_SHORT).show()")
L("                            } catch (e: Exception) { android.widget.Toast.makeText(context, \"保存失败: \", android.widget.Toast.LENGTH_SHORT).show() }")
L("                        }")
L("                    ),")
L("                    contentAlignment = Alignment.Center")
L("                ) {")
L("                    Image(painter = painterResource(id = R.drawable.qr_donate), contentDescription = \"赞赏码\", modifier = Modifier.fillMaxSize(), contentScale = ContentScale.Fit)")
L("                }")
L("                Text(\"长按图片保存到相册\", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f), modifier = Modifier.padding(top = 4.dp))")
L("            }")
L("        }")
L("        Spacer(Modifier.height(24.dp))")
L("    }")
L("}")
L("")

L("// ══════════════════════════════════════════════════════════")
L("// Shared: ExposedDropdownMenu setting")
L("// ══════════════════════════════════════════════════════════")
L("")
L("@OptIn(ExperimentalMaterial3Api::class)")
L("@Composable")
L("private fun DropdownSetting(")
L("    label: String,")
L("    selectedKey: String,")
L("    options: List<Pair<String, String>>,")
L("    onSelect: (String) -> Unit,")
L(") {")
L("    var expanded by remember { mutableStateOf(false) }")
L("    val selectedLabel = options.firstOrNull { it.first == selectedKey }?.second ?: selectedKey")
L("")
L("    ExposedDropdownMenuBox(")
L("        expanded = expanded,")
L("        onExpandedChange = { expanded = it }")
L("    ) {")
L("        OutlinedTextField(")
L("            value = selectedLabel,")
L("            onValueChange = {},")
L("            readOnly = true,")
L("            label = { Text(label) },")
L("            trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = expanded) },")
L("            modifier = Modifier.fillMaxWidth().menuAnchor(),")
L("            singleLine = true")
L("        )")
L("        ExposedDropdownMenu(")
L("            expanded = expanded,")
L("            onDismissRequest = { expanded = false }")
L("        ) {")
L("            options.forEach { (key, display) ->")
L("                DropdownMenuItem(")
L("                    text = { Text(display) },")
L("                    onClick = { onSelect(key); expanded = false },")
L("                    contentPadding = ExposedDropdownMenuDefaults.ItemContentPadding")
L("                )")
L("            }")
L("        }")
L("    }")
L("}")
L("")

# Write the output file
output = '\n'.join(lines)
with open(filepath, 'w', encoding='utf-8') as f:
    f.write(output)
print(f'SettingsScreen.kt written: {len(lines)} lines, {len(output)} bytes')

L(\"package com.quickdaily.ui\")
L(\"\")
L(\"import android.content.Intent\")
L(\"import android.app.Activity\")
L(\"import android.content.ContentValues\")
L(\"import androidx.compose.ui.graphics.toArgb\")
L(\"import android.graphics.BitmapFactory\")
L(\"import android.net.Uri\")
L(\"import android.os.Build\")
L(\"import android.os.Environment\")
L(\"import android.provider.Settings\")
L(\"import android.provider.MediaStore\")
L(\"import androidx.compose.foundation.Image\")
L(\"import androidx.compose.foundation.combinedClickable\")
L(\"import android.graphics.Bitmap\")
L(\"import androidx.compose.foundation.ExperimentalFoundationApi\")
L(\"import java.io.File\")
L(\"import java.io.FileOutputStream\")
L(\"import androidx.activity.compose.rememberLauncherForActivityResult\")
L(\"import androidx.activity.result.contract.ActivityResultContracts\")
L(\"import androidx.compose.foundation.layout.*\")
L(\"import androidx.compose.foundation.rememberScrollState\")
L(\"import androidx.compose.foundation.text.ClickableText\")
L(\"import androidx.compose.foundation.verticalScroll\")
L(\"import androidx.compose.foundation.pager.HorizontalPager\")
L(\"import androidx.compose.foundation.pager.rememberPagerState\")
L(\"import androidx.compose.material.icons.Icons\")
L(\"import androidx.compose.material.icons.automirrored.filled.ArrowBack\")
L(\"import androidx.compose.material.icons.filled.AddAPhoto\")
L(\"import androidx.compose.material.icons.filled.Check\")
L(\"import androidx.compose.material.icons.filled.Description\")
L(\"import androidx.compose.material.icons.filled.EditNote\")
L(\"import androidx.compose.material.icons.filled.FileOpen\")
L(\"import androidx.compose.material.icons.filled.Folder\")
L(\"import androidx.compose.material.icons.filled.FolderOpen\")
L(\"import androidx.compose.material.icons.filled.Widgets\")
L(\"import androidx.compose.material.icons.filled.Update\")
L(\"import androidx.compose.material.icons.filled.AccessibilityNew\")
L(\"import androidx.compose.material.icons.filled.BugReport\")
L(\"import androidx.compose.material.icons.filled.Storage\")
L(\"import androidx.compose.material.icons.filled.Shortcut\")
L(\"import androidx.compose.material.icons.filled.PhotoLibrary\")
L(\"import androidx.compose.material.icons.filled.TextFormat\")
L(\"import androidx.compose.material3.*\")
L(\"import androidx.compose.ui.layout.ContentScale\")
L(\"import androidx.compose.runtime.*\")
L(\"import androidx.compose.ui.Alignment\")
L(\"import androidx.compose.ui.Modifier\")
L(\"import androidx.compose.ui.graphics.asImageBitmap\")
L(\"import androidx.compose.ui.platform.LocalContext\")
L(\"import androidx.compose.ui.res.painterResource\")
L(\"import com.quickdaily.R\")
L(\"import androidx.compose.ui.text.SpanStyle\")
L(\"import androidx.compose.ui.text.buildAnnotatedString\")
L(\"import androidx.compose.ui.text.withStyle\")
L(\"import androidx.compose.ui.unit.dp\")
L(\"import androidx.compose.ui.unit.sp\")
L(\"import androidx.lifecycle.viewmodel.compose.viewModel\")
L(\"import com.quickdaily.AppState\")
L(\"import com.quickdaily.BuildConfig\")
L(\"import com.quickdaily.DiaryConfig\")
L(\"import com.quickdaily.BetaLogger\")
L(\"import com.quickdaily.QuickDailyReadWidget\")
L(\"import com.quickdaily.QuickNoteWidget\")
L(\"import com.quickdaily.TaskWidget\")
L(\"import com.quickdaily.util.ShortcutHelper\")
L(\"import com.quickdaily.util.UriUtil\")
L(\"import kotlinx.coroutines.launch\")
L(\"import com.quickdaily.ui.theme.LocalAppDimensions\")

L(\"\")
L(\"private data class TimestampOption(val key: String, val label: String)\")
L(\"private val timestampOptions = listOf(\")
L(\"    TimestampOption(\\\"none\\\", \\\"无时间戳\\\"),\")
L(\"    TimestampOption(\\\"time_only\\\", \\\"仅时间\\\"),\")
L(\"    TimestampOption(\\\"time_only_seconds\\\", \\\"时间（含秒）\\\"),\")
L(\"    TimestampOption(\\\"list\\\", \\\"无序列表\\\"),\")
L(\"    TimestampOption(\\\"ordered\\\", \\\"有序列表\\\"),\")
L(\"    TimestampOption(\\\"list_time\\\", \\\"列表+时间\\\"),\")
L(\"    TimestampOption(\\\"list_time_seconds\\\", \\\"列表+时间（秒）\\\"),\")
L(\")\")
L(\"\")
L(\"private data class NamingOption(val key: String, val label: String)\")
L(\"private val namingOptions = listOf(\")
L(\"    NamingOption(\\\"timestamp_original\\\", \\\"时间戳_原名\\\"),\")
L(\"    NamingOption(\\\"timestamp_ext\\\", \\\"时间戳+扩展名\\\"),\")
L(\"    NamingOption(\\\"original\\\", \\\"保留原名\\\"),\")
L(\"    NamingOption(\\\"custom\\\", \\\"自定义格式\\\"),\")
L(\")\")
L(\"\")
L(\"private val linkOptions = listOf(\")
L(\"    \\\"described\\\" to \\\"Markdown ![](描述)\\\",\")
L(\"    \\\"obsidian_wikilink\\\" to \\\"Obsidian ![[双向链接]]\\\",\")
L(\")\")
